name: Build and Publish for Cloudways

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Include .htaccess in build output
        run: |
          if [ -f public/.htaccess ]; then
            cp public/.htaccess build/.htaccess
          fi

      - name: Publish build to cloudways-dist branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
          publish_branch: cloudways-dist
          force_orphan: true
          keep_files: false


